name: editing-repo-file
on:
  workflow_dispatch:
    inputs:
      environments:
        type: choice
        options:
          - dev
          - prod
permissions:
  id-token: write
  contents: write

jobs:
  EditFile:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://github.com
    steps:
      - uses: actions/checkout@v3
        with:
          path: devops-pipeline
      - name: Configurar git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "actor+${{ github.actor }}@users.noreply.github.com"
      - name: Modificar archivo
        run: |
          cd devops-pipeline
          echo "Este es el contenido del archivo" > nuevo_archivo.txt
          echo "Texto adicional" >> hello_world.txt
      - name: Subir cambios
        run: |
          cd devops-pipeline
          rm hello_world.txt
          
          git add .
          git commit -m "reemplazando archivo texto al archivo"
          git push
